//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJServicesLibrary.PPIJBoard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PPIJboardMessage", Namespace="http://nihao.fer.hr/")]
    [System.SerializableAttribute()]
    public partial class PPIJboardMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        private System.Nullable<int> ReplyToField;
        
        private System.DateTime PostedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> ReplyTo {
            get {
                return this.ReplyToField;
            }
            set {
                if ((this.ReplyToField.Equals(value) != true)) {
                    this.ReplyToField = value;
                    this.RaisePropertyChanged("ReplyTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Posted {
            get {
                return this.PostedField;
            }
            set {
                if ((this.PostedField.Equals(value) != true)) {
                    this.PostedField = value;
                    this.RaisePropertyChanged("Posted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nihao.fer.hr/", ConfigurationName="PPIJBoard.PPIJboardServiceSoap")]
    public interface PPIJboardServiceSoap {
        
        // CODEGEN: Generating message contract since element name ApplicationKey from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/GetAccessToken", ReplyAction="*")]
        PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponse GetAccessToken(PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://nihao.fer.hr/GetAccessToken", ReplyAction="*")]
        System.IAsyncResult BeginGetAccessToken(PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest request, System.AsyncCallback callback, object asyncState);
        
        PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponse EndGetAccessToken(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/GetMessages", ReplyAction="*")]
        PPIJServicesLibrary.PPIJBoard.GetMessagesResponse GetMessages(PPIJServicesLibrary.PPIJBoard.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://nihao.fer.hr/GetMessages", ReplyAction="*")]
        System.IAsyncResult BeginGetMessages(PPIJServicesLibrary.PPIJBoard.GetMessagesRequest request, System.AsyncCallback callback, object asyncState);
        
        PPIJServicesLibrary.PPIJBoard.GetMessagesResponse EndGetMessages(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/GetLastMessages", ReplyAction="*")]
        PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponse GetLastMessages(PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://nihao.fer.hr/GetLastMessages", ReplyAction="*")]
        System.IAsyncResult BeginGetLastMessages(PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest request, System.AsyncCallback callback, object asyncState);
        
        PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponse EndGetLastMessages(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/PostReply", ReplyAction="*")]
        PPIJServicesLibrary.PPIJBoard.PostReplyResponse PostReply(PPIJServicesLibrary.PPIJBoard.PostReplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://nihao.fer.hr/PostReply", ReplyAction="*")]
        System.IAsyncResult BeginPostReply(PPIJServicesLibrary.PPIJBoard.PostReplyRequest request, System.AsyncCallback callback, object asyncState);
        
        PPIJServicesLibrary.PPIJBoard.PostReplyResponse EndPostReply(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/PostMessage", ReplyAction="*")]
        PPIJServicesLibrary.PPIJBoard.PostMessageResponse PostMessage(PPIJServicesLibrary.PPIJBoard.PostMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://nihao.fer.hr/PostMessage", ReplyAction="*")]
        System.IAsyncResult BeginPostMessage(PPIJServicesLibrary.PPIJBoard.PostMessageRequest request, System.AsyncCallback callback, object asyncState);
        
        PPIJServicesLibrary.PPIJBoard.PostMessageResponse EndPostMessage(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessToken", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequestBody Body;
        
        public GetAccessTokenRequest() {
        }
        
        public GetAccessTokenRequest(PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetAccessTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApplicationKey;
        
        public GetAccessTokenRequestBody() {
        }
        
        public GetAccessTokenRequestBody(string ApplicationKey) {
            this.ApplicationKey = ApplicationKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessTokenResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponseBody Body;
        
        public GetAccessTokenResponse() {
        }
        
        public GetAccessTokenResponse(PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetAccessTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessTokenResult;
        
        public GetAccessTokenResponseBody() {
        }
        
        public GetAccessTokenResponseBody(string GetAccessTokenResult) {
            this.GetAccessTokenResult = GetAccessTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(PPIJServicesLibrary.PPIJBoard.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(PPIJServicesLibrary.PPIJBoard.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> GetMessagesResult;
        
        public GetMessagesResponseBody() {
        }
        
        public GetMessagesResponseBody(System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> GetMessagesResult) {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastMessages", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequestBody Body;
        
        public GetLastMessagesRequest() {
        }
        
        public GetLastMessagesRequest(PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetLastMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public GetLastMessagesRequestBody() {
        }
        
        public GetLastMessagesRequestBody(string token, int count) {
            this.token = token;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastMessagesResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponseBody Body;
        
        public GetLastMessagesResponse() {
        }
        
        public GetLastMessagesResponse(PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetLastMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> GetLastMessagesResult;
        
        public GetLastMessagesResponseBody() {
        }
        
        public GetLastMessagesResponseBody(System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> GetLastMessagesResult) {
            this.GetLastMessagesResult = GetLastMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostReplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostReply", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.PostReplyRequestBody Body;
        
        public PostReplyRequest() {
        }
        
        public PostReplyRequest(PPIJServicesLibrary.PPIJBoard.PostReplyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class PostReplyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> replyTo;
        
        public PostReplyRequestBody() {
        }
        
        public PostReplyRequestBody(string token, string author, string message, System.Nullable<int> replyTo) {
            this.token = token;
            this.author = author;
            this.message = message;
            this.replyTo = replyTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostReplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostReplyResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.PostReplyResponseBody Body;
        
        public PostReplyResponse() {
        }
        
        public PostReplyResponse(PPIJServicesLibrary.PPIJBoard.PostReplyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostReplyResponseBody {
        
        public PostReplyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostMessage", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.PostMessageRequestBody Body;
        
        public PostMessageRequest() {
        }
        
        public PostMessageRequest(PPIJServicesLibrary.PPIJBoard.PostMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class PostMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public PostMessageRequestBody() {
        }
        
        public PostMessageRequestBody(string token, string author, string message) {
            this.token = token;
            this.author = author;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostMessageResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public PPIJServicesLibrary.PPIJBoard.PostMessageResponseBody Body;
        
        public PostMessageResponse() {
        }
        
        public PostMessageResponse(PPIJServicesLibrary.PPIJBoard.PostMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostMessageResponseBody {
        
        public PostMessageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PPIJboardServiceSoapChannel : PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAccessTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAccessTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PPIJboardServiceSoapClient : System.ServiceModel.ClientBase<PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap>, PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap {
        
        private BeginOperationDelegate onBeginGetAccessTokenDelegate;
        
        private EndOperationDelegate onEndGetAccessTokenDelegate;
        
        private System.Threading.SendOrPostCallback onGetAccessTokenCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMessagesDelegate;
        
        private EndOperationDelegate onEndGetMessagesDelegate;
        
        private System.Threading.SendOrPostCallback onGetMessagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLastMessagesDelegate;
        
        private EndOperationDelegate onEndGetLastMessagesDelegate;
        
        private System.Threading.SendOrPostCallback onGetLastMessagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostReplyDelegate;
        
        private EndOperationDelegate onEndPostReplyDelegate;
        
        private System.Threading.SendOrPostCallback onPostReplyCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostMessageDelegate;
        
        private EndOperationDelegate onEndPostMessageDelegate;
        
        private System.Threading.SendOrPostCallback onPostMessageCompletedDelegate;
        
        public PPIJboardServiceSoapClient() {
        }
        
        public PPIJboardServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PPIJboardServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPIJboardServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPIJboardServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAccessTokenCompletedEventArgs> GetAccessTokenCompleted;
        
        public event System.EventHandler<GetMessagesCompletedEventArgs> GetMessagesCompleted;
        
        public event System.EventHandler<GetLastMessagesCompletedEventArgs> GetLastMessagesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PostReplyCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PostMessageCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.GetAccessToken(PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest request) {
            return base.Channel.GetAccessToken(request);
        }
        
        public string GetAccessToken(string ApplicationKey) {
            PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest inValue = new PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequestBody();
            inValue.Body.ApplicationKey = ApplicationKey;
            PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).GetAccessToken(inValue);
            return retVal.Body.GetAccessTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.BeginGetAccessToken(PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAccessToken(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAccessToken(string ApplicationKey, System.AsyncCallback callback, object asyncState) {
            PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest inValue = new PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.GetAccessTokenRequestBody();
            inValue.Body.ApplicationKey = ApplicationKey;
            return ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).BeginGetAccessToken(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.EndGetAccessToken(System.IAsyncResult result) {
            return base.Channel.EndGetAccessToken(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetAccessToken(System.IAsyncResult result) {
            PPIJServicesLibrary.PPIJBoard.GetAccessTokenResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).EndGetAccessToken(result);
            return retVal.Body.GetAccessTokenResult;
        }
        
        private System.IAsyncResult OnBeginGetAccessToken(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ApplicationKey = ((string)(inValues[0]));
            return this.BeginGetAccessToken(ApplicationKey, callback, asyncState);
        }
        
        private object[] OnEndGetAccessToken(System.IAsyncResult result) {
            string retVal = this.EndGetAccessToken(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAccessTokenCompleted(object state) {
            if ((this.GetAccessTokenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAccessTokenCompleted(this, new GetAccessTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAccessTokenAsync(string ApplicationKey) {
            this.GetAccessTokenAsync(ApplicationKey, null);
        }
        
        public void GetAccessTokenAsync(string ApplicationKey, object userState) {
            if ((this.onBeginGetAccessTokenDelegate == null)) {
                this.onBeginGetAccessTokenDelegate = new BeginOperationDelegate(this.OnBeginGetAccessToken);
            }
            if ((this.onEndGetAccessTokenDelegate == null)) {
                this.onEndGetAccessTokenDelegate = new EndOperationDelegate(this.OnEndGetAccessToken);
            }
            if ((this.onGetAccessTokenCompletedDelegate == null)) {
                this.onGetAccessTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAccessTokenCompleted);
            }
            base.InvokeAsync(this.onBeginGetAccessTokenDelegate, new object[] {
                        ApplicationKey}, this.onEndGetAccessTokenDelegate, this.onGetAccessTokenCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.GetMessagesResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.GetMessages(PPIJServicesLibrary.PPIJBoard.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> GetMessages(string token) {
            PPIJServicesLibrary.PPIJBoard.GetMessagesRequest inValue = new PPIJServicesLibrary.PPIJBoard.GetMessagesRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.GetMessagesRequestBody();
            inValue.Body.token = token;
            PPIJServicesLibrary.PPIJBoard.GetMessagesResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).GetMessages(inValue);
            return retVal.Body.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.BeginGetMessages(PPIJServicesLibrary.PPIJBoard.GetMessagesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMessages(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMessages(string token, System.AsyncCallback callback, object asyncState) {
            PPIJServicesLibrary.PPIJBoard.GetMessagesRequest inValue = new PPIJServicesLibrary.PPIJBoard.GetMessagesRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.GetMessagesRequestBody();
            inValue.Body.token = token;
            return ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).BeginGetMessages(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.GetMessagesResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.EndGetMessages(System.IAsyncResult result) {
            return base.Channel.EndGetMessages(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> EndGetMessages(System.IAsyncResult result) {
            PPIJServicesLibrary.PPIJBoard.GetMessagesResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).EndGetMessages(result);
            return retVal.Body.GetMessagesResult;
        }
        
        private System.IAsyncResult OnBeginGetMessages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            return this.BeginGetMessages(token, callback, asyncState);
        }
        
        private object[] OnEndGetMessages(System.IAsyncResult result) {
            System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> retVal = this.EndGetMessages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMessagesCompleted(object state) {
            if ((this.GetMessagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMessagesCompleted(this, new GetMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMessagesAsync(string token) {
            this.GetMessagesAsync(token, null);
        }
        
        public void GetMessagesAsync(string token, object userState) {
            if ((this.onBeginGetMessagesDelegate == null)) {
                this.onBeginGetMessagesDelegate = new BeginOperationDelegate(this.OnBeginGetMessages);
            }
            if ((this.onEndGetMessagesDelegate == null)) {
                this.onEndGetMessagesDelegate = new EndOperationDelegate(this.OnEndGetMessages);
            }
            if ((this.onGetMessagesCompletedDelegate == null)) {
                this.onGetMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMessagesCompleted);
            }
            base.InvokeAsync(this.onBeginGetMessagesDelegate, new object[] {
                        token}, this.onEndGetMessagesDelegate, this.onGetMessagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.GetLastMessages(PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest request) {
            return base.Channel.GetLastMessages(request);
        }
        
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> GetLastMessages(string token, int count) {
            PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest inValue = new PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequestBody();
            inValue.Body.token = token;
            inValue.Body.count = count;
            PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).GetLastMessages(inValue);
            return retVal.Body.GetLastMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.BeginGetLastMessages(PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastMessages(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetLastMessages(string token, int count, System.AsyncCallback callback, object asyncState) {
            PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest inValue = new PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.GetLastMessagesRequestBody();
            inValue.Body.token = token;
            inValue.Body.count = count;
            return ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).BeginGetLastMessages(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.EndGetLastMessages(System.IAsyncResult result) {
            return base.Channel.EndGetLastMessages(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> EndGetLastMessages(System.IAsyncResult result) {
            PPIJServicesLibrary.PPIJBoard.GetLastMessagesResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).EndGetLastMessages(result);
            return retVal.Body.GetLastMessagesResult;
        }
        
        private System.IAsyncResult OnBeginGetLastMessages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            int count = ((int)(inValues[1]));
            return this.BeginGetLastMessages(token, count, callback, asyncState);
        }
        
        private object[] OnEndGetLastMessages(System.IAsyncResult result) {
            System.Collections.Generic.List<PPIJServicesLibrary.PPIJBoard.PPIJboardMessage> retVal = this.EndGetLastMessages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastMessagesCompleted(object state) {
            if ((this.GetLastMessagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastMessagesCompleted(this, new GetLastMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastMessagesAsync(string token, int count) {
            this.GetLastMessagesAsync(token, count, null);
        }
        
        public void GetLastMessagesAsync(string token, int count, object userState) {
            if ((this.onBeginGetLastMessagesDelegate == null)) {
                this.onBeginGetLastMessagesDelegate = new BeginOperationDelegate(this.OnBeginGetLastMessages);
            }
            if ((this.onEndGetLastMessagesDelegate == null)) {
                this.onEndGetLastMessagesDelegate = new EndOperationDelegate(this.OnEndGetLastMessages);
            }
            if ((this.onGetLastMessagesCompletedDelegate == null)) {
                this.onGetLastMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastMessagesCompleted);
            }
            base.InvokeAsync(this.onBeginGetLastMessagesDelegate, new object[] {
                        token,
                        count}, this.onEndGetLastMessagesDelegate, this.onGetLastMessagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.PostReplyResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.PostReply(PPIJServicesLibrary.PPIJBoard.PostReplyRequest request) {
            return base.Channel.PostReply(request);
        }
        
        public void PostReply(string token, string author, string message, System.Nullable<int> replyTo) {
            PPIJServicesLibrary.PPIJBoard.PostReplyRequest inValue = new PPIJServicesLibrary.PPIJBoard.PostReplyRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.PostReplyRequestBody();
            inValue.Body.token = token;
            inValue.Body.author = author;
            inValue.Body.message = message;
            inValue.Body.replyTo = replyTo;
            PPIJServicesLibrary.PPIJBoard.PostReplyResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).PostReply(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.BeginPostReply(PPIJServicesLibrary.PPIJBoard.PostReplyRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostReply(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPostReply(string token, string author, string message, System.Nullable<int> replyTo, System.AsyncCallback callback, object asyncState) {
            PPIJServicesLibrary.PPIJBoard.PostReplyRequest inValue = new PPIJServicesLibrary.PPIJBoard.PostReplyRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.PostReplyRequestBody();
            inValue.Body.token = token;
            inValue.Body.author = author;
            inValue.Body.message = message;
            inValue.Body.replyTo = replyTo;
            return ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).BeginPostReply(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.PostReplyResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.EndPostReply(System.IAsyncResult result) {
            return base.Channel.EndPostReply(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndPostReply(System.IAsyncResult result) {
            PPIJServicesLibrary.PPIJBoard.PostReplyResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).EndPostReply(result);
        }
        
        private System.IAsyncResult OnBeginPostReply(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            string author = ((string)(inValues[1]));
            string message = ((string)(inValues[2]));
            System.Nullable<int> replyTo = ((System.Nullable<int>)(inValues[3]));
            return this.BeginPostReply(token, author, message, replyTo, callback, asyncState);
        }
        
        private object[] OnEndPostReply(System.IAsyncResult result) {
            this.EndPostReply(result);
            return null;
        }
        
        private void OnPostReplyCompleted(object state) {
            if ((this.PostReplyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostReplyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostReplyAsync(string token, string author, string message, System.Nullable<int> replyTo) {
            this.PostReplyAsync(token, author, message, replyTo, null);
        }
        
        public void PostReplyAsync(string token, string author, string message, System.Nullable<int> replyTo, object userState) {
            if ((this.onBeginPostReplyDelegate == null)) {
                this.onBeginPostReplyDelegate = new BeginOperationDelegate(this.OnBeginPostReply);
            }
            if ((this.onEndPostReplyDelegate == null)) {
                this.onEndPostReplyDelegate = new EndOperationDelegate(this.OnEndPostReply);
            }
            if ((this.onPostReplyCompletedDelegate == null)) {
                this.onPostReplyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostReplyCompleted);
            }
            base.InvokeAsync(this.onBeginPostReplyDelegate, new object[] {
                        token,
                        author,
                        message,
                        replyTo}, this.onEndPostReplyDelegate, this.onPostReplyCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.PostMessageResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.PostMessage(PPIJServicesLibrary.PPIJBoard.PostMessageRequest request) {
            return base.Channel.PostMessage(request);
        }
        
        public void PostMessage(string token, string author, string message) {
            PPIJServicesLibrary.PPIJBoard.PostMessageRequest inValue = new PPIJServicesLibrary.PPIJBoard.PostMessageRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.PostMessageRequestBody();
            inValue.Body.token = token;
            inValue.Body.author = author;
            inValue.Body.message = message;
            PPIJServicesLibrary.PPIJBoard.PostMessageResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).PostMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.BeginPostMessage(PPIJServicesLibrary.PPIJBoard.PostMessageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostMessage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPostMessage(string token, string author, string message, System.AsyncCallback callback, object asyncState) {
            PPIJServicesLibrary.PPIJBoard.PostMessageRequest inValue = new PPIJServicesLibrary.PPIJBoard.PostMessageRequest();
            inValue.Body = new PPIJServicesLibrary.PPIJBoard.PostMessageRequestBody();
            inValue.Body.token = token;
            inValue.Body.author = author;
            inValue.Body.message = message;
            return ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).BeginPostMessage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PPIJServicesLibrary.PPIJBoard.PostMessageResponse PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap.EndPostMessage(System.IAsyncResult result) {
            return base.Channel.EndPostMessage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndPostMessage(System.IAsyncResult result) {
            PPIJServicesLibrary.PPIJBoard.PostMessageResponse retVal = ((PPIJServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).EndPostMessage(result);
        }
        
        private System.IAsyncResult OnBeginPostMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            string author = ((string)(inValues[1]));
            string message = ((string)(inValues[2]));
            return this.BeginPostMessage(token, author, message, callback, asyncState);
        }
        
        private object[] OnEndPostMessage(System.IAsyncResult result) {
            this.EndPostMessage(result);
            return null;
        }
        
        private void OnPostMessageCompleted(object state) {
            if ((this.PostMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostMessageAsync(string token, string author, string message) {
            this.PostMessageAsync(token, author, message, null);
        }
        
        public void PostMessageAsync(string token, string author, string message, object userState) {
            if ((this.onBeginPostMessageDelegate == null)) {
                this.onBeginPostMessageDelegate = new BeginOperationDelegate(this.OnBeginPostMessage);
            }
            if ((this.onEndPostMessageDelegate == null)) {
                this.onEndPostMessageDelegate = new EndOperationDelegate(this.OnEndPostMessage);
            }
            if ((this.onPostMessageCompletedDelegate == null)) {
                this.onPostMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostMessageCompleted);
            }
            base.InvokeAsync(this.onBeginPostMessageDelegate, new object[] {
                        token,
                        author,
                        message}, this.onEndPostMessageDelegate, this.onPostMessageCompletedDelegate, userState);
        }
    }
}
