//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesLibrary.PPIJBoard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PPIJboardMessage", Namespace="http://nihao.fer.hr/")]
    [System.SerializableAttribute()]
    public partial class PPIJboardMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        private int IdField;
        
        private System.DateTime PostedField;
        
        private System.Nullable<int> ReplyToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Posted {
            get {
                return this.PostedField;
            }
            set {
                if ((this.PostedField.Equals(value) != true)) {
                    this.PostedField = value;
                    this.RaisePropertyChanged("Posted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ReplyTo {
            get {
                return this.ReplyToField;
            }
            set {
                if ((this.ReplyToField.Equals(value) != true)) {
                    this.ReplyToField = value;
                    this.RaisePropertyChanged("ReplyTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nihao.fer.hr/", ConfigurationName="PPIJBoard.PPIJboardServiceSoap")]
    public interface PPIJboardServiceSoap {
        
        // CODEGEN: Generating message contract since element name ApplicationKey from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/GetAccessToken", ReplyAction="*")]
        ServicesLibrary.PPIJBoard.GetAccessTokenResponse GetAccessToken(ServicesLibrary.PPIJBoard.GetAccessTokenRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/GetMessages", ReplyAction="*")]
        ServicesLibrary.PPIJBoard.GetMessagesResponse GetMessages(ServicesLibrary.PPIJBoard.GetMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/GetLastMessages", ReplyAction="*")]
        ServicesLibrary.PPIJBoard.GetLastMessagesResponse GetLastMessages(ServicesLibrary.PPIJBoard.GetLastMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/PostReply", ReplyAction="*")]
        ServicesLibrary.PPIJBoard.PostReplyResponse PostReply(ServicesLibrary.PPIJBoard.PostReplyRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://nihao.fer.hr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nihao.fer.hr/PostMessage", ReplyAction="*")]
        ServicesLibrary.PPIJBoard.PostMessageResponse PostMessage(ServicesLibrary.PPIJBoard.PostMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessToken", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.GetAccessTokenRequestBody Body;
        
        public GetAccessTokenRequest() {
        }
        
        public GetAccessTokenRequest(ServicesLibrary.PPIJBoard.GetAccessTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetAccessTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApplicationKey;
        
        public GetAccessTokenRequestBody() {
        }
        
        public GetAccessTokenRequestBody(string ApplicationKey) {
            this.ApplicationKey = ApplicationKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessTokenResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.GetAccessTokenResponseBody Body;
        
        public GetAccessTokenResponse() {
        }
        
        public GetAccessTokenResponse(ServicesLibrary.PPIJBoard.GetAccessTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetAccessTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessTokenResult;
        
        public GetAccessTokenResponseBody() {
        }
        
        public GetAccessTokenResponseBody(string GetAccessTokenResult) {
            this.GetAccessTokenResult = GetAccessTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(ServicesLibrary.PPIJBoard.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(ServicesLibrary.PPIJBoard.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicesLibrary.PPIJBoard.PPIJboardMessage[] GetMessagesResult;
        
        public GetMessagesResponseBody() {
        }
        
        public GetMessagesResponseBody(ServicesLibrary.PPIJBoard.PPIJboardMessage[] GetMessagesResult) {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastMessages", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.GetLastMessagesRequestBody Body;
        
        public GetLastMessagesRequest() {
        }
        
        public GetLastMessagesRequest(ServicesLibrary.PPIJBoard.GetLastMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetLastMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public GetLastMessagesRequestBody() {
        }
        
        public GetLastMessagesRequestBody(string token, int count) {
            this.token = token;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastMessagesResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.GetLastMessagesResponseBody Body;
        
        public GetLastMessagesResponse() {
        }
        
        public GetLastMessagesResponse(ServicesLibrary.PPIJBoard.GetLastMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class GetLastMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicesLibrary.PPIJBoard.PPIJboardMessage[] GetLastMessagesResult;
        
        public GetLastMessagesResponseBody() {
        }
        
        public GetLastMessagesResponseBody(ServicesLibrary.PPIJBoard.PPIJboardMessage[] GetLastMessagesResult) {
            this.GetLastMessagesResult = GetLastMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostReplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostReply", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.PostReplyRequestBody Body;
        
        public PostReplyRequest() {
        }
        
        public PostReplyRequest(ServicesLibrary.PPIJBoard.PostReplyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class PostReplyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> replyTo;
        
        public PostReplyRequestBody() {
        }
        
        public PostReplyRequestBody(string token, string author, string message, System.Nullable<int> replyTo) {
            this.token = token;
            this.author = author;
            this.message = message;
            this.replyTo = replyTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostReplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostReplyResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.PostReplyResponseBody Body;
        
        public PostReplyResponse() {
        }
        
        public PostReplyResponse(ServicesLibrary.PPIJBoard.PostReplyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostReplyResponseBody {
        
        public PostReplyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostMessage", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.PostMessageRequestBody Body;
        
        public PostMessageRequest() {
        }
        
        public PostMessageRequest(ServicesLibrary.PPIJBoard.PostMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nihao.fer.hr/")]
    public partial class PostMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public PostMessageRequestBody() {
        }
        
        public PostMessageRequestBody(string token, string author, string message) {
            this.token = token;
            this.author = author;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostMessageResponse", Namespace="http://nihao.fer.hr/", Order=0)]
        public ServicesLibrary.PPIJBoard.PostMessageResponseBody Body;
        
        public PostMessageResponse() {
        }
        
        public PostMessageResponse(ServicesLibrary.PPIJBoard.PostMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostMessageResponseBody {
        
        public PostMessageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PPIJboardServiceSoapChannel : ServicesLibrary.PPIJBoard.PPIJboardServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PPIJboardServiceSoapClient : System.ServiceModel.ClientBase<ServicesLibrary.PPIJBoard.PPIJboardServiceSoap>, ServicesLibrary.PPIJBoard.PPIJboardServiceSoap {
        
        public PPIJboardServiceSoapClient() {
        }
        
        public PPIJboardServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PPIJboardServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPIJboardServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPIJboardServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicesLibrary.PPIJBoard.GetAccessTokenResponse ServicesLibrary.PPIJBoard.PPIJboardServiceSoap.GetAccessToken(ServicesLibrary.PPIJBoard.GetAccessTokenRequest request) {
            return base.Channel.GetAccessToken(request);
        }
        
        public string GetAccessToken(string ApplicationKey) {
            ServicesLibrary.PPIJBoard.GetAccessTokenRequest inValue = new ServicesLibrary.PPIJBoard.GetAccessTokenRequest();
            inValue.Body = new ServicesLibrary.PPIJBoard.GetAccessTokenRequestBody();
            inValue.Body.ApplicationKey = ApplicationKey;
            ServicesLibrary.PPIJBoard.GetAccessTokenResponse retVal = ((ServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).GetAccessToken(inValue);
            return retVal.Body.GetAccessTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicesLibrary.PPIJBoard.GetMessagesResponse ServicesLibrary.PPIJBoard.PPIJboardServiceSoap.GetMessages(ServicesLibrary.PPIJBoard.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public ServicesLibrary.PPIJBoard.PPIJboardMessage[] GetMessages(string token) {
            ServicesLibrary.PPIJBoard.GetMessagesRequest inValue = new ServicesLibrary.PPIJBoard.GetMessagesRequest();
            inValue.Body = new ServicesLibrary.PPIJBoard.GetMessagesRequestBody();
            inValue.Body.token = token;
            ServicesLibrary.PPIJBoard.GetMessagesResponse retVal = ((ServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).GetMessages(inValue);
            return retVal.Body.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicesLibrary.PPIJBoard.GetLastMessagesResponse ServicesLibrary.PPIJBoard.PPIJboardServiceSoap.GetLastMessages(ServicesLibrary.PPIJBoard.GetLastMessagesRequest request) {
            return base.Channel.GetLastMessages(request);
        }
        
        public ServicesLibrary.PPIJBoard.PPIJboardMessage[] GetLastMessages(string token, int count) {
            ServicesLibrary.PPIJBoard.GetLastMessagesRequest inValue = new ServicesLibrary.PPIJBoard.GetLastMessagesRequest();
            inValue.Body = new ServicesLibrary.PPIJBoard.GetLastMessagesRequestBody();
            inValue.Body.token = token;
            inValue.Body.count = count;
            ServicesLibrary.PPIJBoard.GetLastMessagesResponse retVal = ((ServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).GetLastMessages(inValue);
            return retVal.Body.GetLastMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicesLibrary.PPIJBoard.PostReplyResponse ServicesLibrary.PPIJBoard.PPIJboardServiceSoap.PostReply(ServicesLibrary.PPIJBoard.PostReplyRequest request) {
            return base.Channel.PostReply(request);
        }
        
        public void PostReply(string token, string author, string message, System.Nullable<int> replyTo) {
            ServicesLibrary.PPIJBoard.PostReplyRequest inValue = new ServicesLibrary.PPIJBoard.PostReplyRequest();
            inValue.Body = new ServicesLibrary.PPIJBoard.PostReplyRequestBody();
            inValue.Body.token = token;
            inValue.Body.author = author;
            inValue.Body.message = message;
            inValue.Body.replyTo = replyTo;
            ServicesLibrary.PPIJBoard.PostReplyResponse retVal = ((ServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).PostReply(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicesLibrary.PPIJBoard.PostMessageResponse ServicesLibrary.PPIJBoard.PPIJboardServiceSoap.PostMessage(ServicesLibrary.PPIJBoard.PostMessageRequest request) {
            return base.Channel.PostMessage(request);
        }
        
        public void PostMessage(string token, string author, string message) {
            ServicesLibrary.PPIJBoard.PostMessageRequest inValue = new ServicesLibrary.PPIJBoard.PostMessageRequest();
            inValue.Body = new ServicesLibrary.PPIJBoard.PostMessageRequestBody();
            inValue.Body.token = token;
            inValue.Body.author = author;
            inValue.Body.message = message;
            ServicesLibrary.PPIJBoard.PostMessageResponse retVal = ((ServicesLibrary.PPIJBoard.PPIJboardServiceSoap)(this)).PostMessage(inValue);
        }
    }
}
